services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: music-web-app
    restart: always
    ports:
      - 3000:3000
    command: bash -c /usr/src/app/start.sh
    env_file: .env

  postgres:
    image: postgres:latest
    container_name: music-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: music_db
    ports:
      - "8001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "81:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml

volumes:
  postgres_data:

