openapi: 3.0.0
info:
  title: Music API
  version: 1.0.0
  description: REST API for managing music tracks
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /tracks:
    get:
      summary: List all tracks
      responses:
        '200':
          description: A list of tracks
    post:
      summary: Create a new track
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Track'
      responses:
        '201':
          description: Created
  /tracks/{id}:
    get:
      summary: Get a track by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Track ID
      responses:
        '200':
          description: A track object
        '404':
          description: Track not found
    put:
      summary: Update a track by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Track ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Track'
      responses:
        '200':
          description: Updated
        '404':
          description: Track not found
    delete:
      summary: Delete a track by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Track ID
      responses:
        '204':
          description: No content
components:
  schemas:
    Track:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        artist:
          type: string
        album:
          type: string
